version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    networks:
      - proxy_default
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/:/etc/nginx/conf.d/
    environment:
      HOST_IP: ${HOST_IP}

networks:
  "proxy_default":
    external: true