version: "3"

networks:
    proxy:
        external: true
        name: proxy_default
    app:
        external: false
        name: ${PROJECT_NAME}_default

services:
    imaginary:
        image: h2non/imaginary:latest
        command: -enable-url-source -mount /mnt/data
        volumes:
            - ${STORE_ROOT_PATH}:/mnt/data
            - ${STORE_THUMBNAIL_PATH}:/mnt/thumbs
        networks:
            - proxy
            - app
        environment:
            - PORT=9000
            - VIRTUAL_HOST=images.${SERVER_VIRTUAL_HOST}
            - VIRTUAL_PORT=9000
            - SERVER_PORT=${SERVER_PORT}
